package bridgempp.state;

public enum Event
{
	ENDPOINT_CREATED,
	ENDPOINT_CONNECTED,
	ENDPOINT_DISCONNECTED,
	ENDPOINT_REMOVED,
	BRIDGEMPP_STARTUP,
	BRIDGEMPP_SHUTDOWN,
	SERVICE_LOADED,
	SERVICE_UNLOADED,
	SERVICE_CONNECTED,
	SERVICE_DISCONNECTED, 
	LOG, 
	MESSAGE
}